spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  application:
    name: user-module
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: me
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update   # ?? ??? update, ??? create / ??? validate ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8085

springdoc:
  api-docs:
    enabled: true  # API ??(`/v3/api-docs`) ??? ?? (???: true)
    path: /v3/api-docs/auth  # API ??? ????? ?? (???: /v3/api-docs)
    groups.enabled: true  # ?? ?? API ??? ???? ??

  swagger-ui:
    enabled: true  # Swagger UI ??? ?? (???: true)
    path: /swagger-ui.html  # Swagger UI ?? ?? ?? (???: /swagger-ui.html)
    operationsSorter: method  # API ?? ?? (alpha: ????, method: HTTP ??? ?)
    tagsSorter: alpha  # ?? ?? ?? (alpha: ???? ??)
    display-request-duration: true  # ?? ?? ?? ?? ??
    doc-expansion: none  # Swagger UI?? API ??? ?? ?? ?? (none: ??, list: ??, full: ?? ??)
    persistAuthorization: true  # ??? ???? ??? Authorization ?? ?? ??
    defaultModelsExpandDepth: -1  # ?? ???? ?? ?? ?? (-1?? ?? ???? ??)

  paths-to-match:  # OpenAPI ???? ??? ????? ??
    - /**  # /api? ???? ?? ?? ??
  cache:
    disabled: true  # OpenAPI ??? ?? ???? (???: false)
  show-actuator: false


jwt:
  secret : q4+1b+3PZPf7uUm7iv1u3fT1NYZQhMXnxZ0qFz1eN5U=
  access-expiration-time: 900000
  refresh-expiration-time: 604800000