spring:
  application:
    name: data-process-module

server:
  port: 8082

springdoc:
  api-docs:
    enabled: true  # API ??(`/v3/api-docs`) ??? ?? (???: true)
    path: /data  # API ??? ????? ?? (???: /v3/api-docs)
    groups.enabled: true  # ?? ?? API ??? ???? ??

  swagger-ui:
    enabled: true  # Swagger UI ??? ?? (???: true)
    path: /swagger-ui.html  # Swagger UI ?? ?? ?? (???: /swagger-ui.html)
    operationsSorter: method  # API ?? ?? (alpha: ????, method: HTTP ??? ?)
    tagsSorter: alpha  # ?? ?? ?? (alpha: ???? ??)
    display-request-duration: true  # ?? ?? ?? ?? ??
    doc-expansion: none  # Swagger UI?? API ??? ?? ?? ?? (none: ??, list: ??, full: ?? ??)
    persistAuthorization: true  # ??? ???? ??? Authorization ?? ?? ??
    defaultModelsExpandDepth: -1  # ?? ???? ?? ?? ?? (-1?? ?? ???? ??)

  paths-to-match:  # OpenAPI ???? ??? ????? ??
    - /**  # /api? ???? ?? ?? ??
  cache:
    disabled: true  # OpenAPI ??? ?? ???? (???: false)
  show-actuator: false